version: '3.8'
services:
  backend:
    image: veenote:v1
    container_name: veenote_backend
    ports:
      - "8000:8000"

  
  
  mongodb:
    image: mongo:4.4
    container_name: mongodb_veenote
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: