name: Docker Compose CI

on:
  pull_request:
    branches:
      - main

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run with Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    - name: Check running containers
      run: docker ps
